In [2]:
from transformers import pipeline
sentiment_analyzer = pipeline("sentiment-analysis")



No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [3]:
sentiment_analyzer("'the movie really bad")

[{'label': 'NEGATIVE', 'score': 0.9998028874397278}]

In [4]:
from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline
model_id='cardiffnlp/twitter-roberta-base-sentiment-latest'
tokenizer=AutoTokenizer.from_pretrained(model_id)
#model=AutoModelForTokenClassification.from_pretrained(model_id)
#ner_model=pipeline("ner",model=model,tokenizer=tokenizer)

config.json:   0%|          | 0.00/929 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [5]:
docs=['I like this movie','very bad movie']
inputs=tokenizer(docs,padding=True,truncation=True,return_tensors='tf')
inputs

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


{'input_ids': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[   0,  100,  101,   42, 1569,    2],
       [   0, 5525, 1099, 1569,    2,    1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0]], dtype=int32)>}

In [6]:
tokenizer.tokenize(docs[1])

['very', 'Ġbad', 'Ġmovie']

In [7]:
from transformers import TFAutoModelForSequenceClassification
model=TFAutoModelForSequenceClassification.from_pretrained(model_id)
outputs=model(inputs)
outputs

tf_model.h5:   0%|          | 0.00/499M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFRobertaForSequenceClassification.

Some layers of TFRobertaForSequenceClassification were not initialized from the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.0027841 , -0.11310594, -0.05336474],
       [ 0.21606913, -0.30623615,  0.05803801]], dtype=float32)>, hidden_states=None, attentions=None)

In [9]:
model.config.id2label

{0: 'negative', 1: 'neutral', 2: 'positive'}

In [3]:
from huggingface_hub import notebook_login
notebook_login()

In [2]:
from transformers import AutoTokenizer, AutoModelForCausalLM
model_name='meta-llama/Llama-2-7b-chat-hf'
tokenizer=AutoTokenizer.from_pretrained(model_name)
##model=AutoModelForCausalLM.from_pretrained(model_name)
#tokenizer=AutoTokenizer.from_pretrained(model_id)
#model=TFAutoModelForSequenceClassification.from_pretrained(model_id)

In [1]:
pip install transformers


In [ ]:
model=AutoModelForCausalLM.from_pretrained(model_name)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]